### ISSUE TITLE
honk honk

### ISSUE THREAD

**Issue by Willy-JL** [VehanRajintha/Spoof-your-Android-as-Apple-BLE-Proximity-Pairing-devise#1]
where are the credits to the original author, @ECTO-1A ? or his repo https://github.com/ECTO-1A/AppleJuice ?

dont try to deny it, your packets contain nearby action flags 0xc1, which is not found on any apple devices, and was put by ecto for testing, and now makes it clear where these come from.

also, check your spelling of "devise".

**Comment by VehanRajintha** [comment]
Ok

**Comment by VehanRajintha** [comment]
Ok
